# Generated by Django 5.2 on 2025-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('name_local_gov', models.CharField(max_length=2000, verbose_name='Найменування органу місцевого самоврядування')),
                ('code_region', models.CharField(max_length=2, verbose_name='Код області')),
                ('name_budg', models.CharField(max_length=2000, verbose_name='Найменування бюджету')),
                ('katottg', models.CharField(blank=True, max_length=20, null=True, verbose_name='КАТОТТГ')),
                ('code_budg', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код бюджету')),
                ('sign_budg', models.CharField(max_length=16, verbose_name='Ознака бюджету')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджети',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('code_region', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код області')),
                ('name', models.CharField(max_length=100, verbose_name='Назва області')),
            ],
            options={
                'verbose_name': 'Області',
                'verbose_name_plural': 'Області',
            },
        ),
    ]
