# Generated by Django 5.2 on 2025-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('name_local_gov', models.CharField(max_length=2000, primary_key=True, serialize=False, verbose_name='Найменування органу місцевого самоврядування')),
                ('code_region', models.CharField(max_length=2, verbose_name='Код території')),
                ('name_budg', models.CharField(max_length=2000, verbose_name='Найменування бюджету')),
                ('koatuu', models.CharField(max_length=10, verbose_name='КОАТУУ')),
                ('code_budg', models.CharField(max_length=11, unique=True, verbose_name='Код бюджету')),
                ('sign_budg', models.CharField(max_length=16, verbose_name='Ознака бюджету')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджети',
            },
        ),
    ]
