# Generated by Django 5.2 on 2025-04-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_period', models.CharField(max_length=7)),
                ('fund_typ', models.CharField(max_length=1)),
                ('cod_budget', models.CharField(max_length=20)),
                ('cod_inco', models.CharField(max_length=20)),
                ('zat_amt', models.FloatField(null=True)),
                ('fakt_amt', models.FloatField(null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.budgets')),
            ],
            options={
                'db_table': 'income_history',
                'unique_together': {('budget', 'rep_period', 'fund_typ', 'cod_inco')},
            },
        ),
    ]
